/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/insight`; params?: Router.UnknownInputParams; } | { pathname: `/screens/language`; params?: Router.UnknownInputParams; } | { pathname: `/screens/layout`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/resetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/signin`; params?: Router.UnknownInputParams; } | { pathname: `/screens/stocks`; params?: Router.UnknownInputParams; } | { pathname: `/screens/transaction`; params?: Router.UnknownInputParams; } | { pathname: `/screens/verification`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/forgetpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/home`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/insight`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/language`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/resetpassword`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/stocks`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/transaction`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/verification`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/forgetpassword${`?${string}` | `#${string}` | ''}` | `/screens/home${`?${string}` | `#${string}` | ''}` | `/screens/insight${`?${string}` | `#${string}` | ''}` | `/screens/language${`?${string}` | `#${string}` | ''}` | `/screens/layout${`?${string}` | `#${string}` | ''}` | `/screens/login${`?${string}` | `#${string}` | ''}` | `/screens/resetpassword${`?${string}` | `#${string}` | ''}` | `/screens/signin${`?${string}` | `#${string}` | ''}` | `/screens/stocks${`?${string}` | `#${string}` | ''}` | `/screens/transaction${`?${string}` | `#${string}` | ''}` | `/screens/verification${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/home`; params?: Router.UnknownInputParams; } | { pathname: `/screens/insight`; params?: Router.UnknownInputParams; } | { pathname: `/screens/language`; params?: Router.UnknownInputParams; } | { pathname: `/screens/layout`; params?: Router.UnknownInputParams; } | { pathname: `/screens/login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/resetpassword`; params?: Router.UnknownInputParams; } | { pathname: `/screens/signin`; params?: Router.UnknownInputParams; } | { pathname: `/screens/stocks`; params?: Router.UnknownInputParams; } | { pathname: `/screens/transaction`; params?: Router.UnknownInputParams; } | { pathname: `/screens/verification`; params?: Router.UnknownInputParams; };
    }
  }
}
